### ISSUE TITLE
Feature Request : Fail on Threshold parameter

### ISSUE THREAD

**Issue by dylan-asos** [snyk/snyk-azure-pipelines-task#137]
Feature Request : Introduce a new parameter, **failOnThreshold**, which should allow the operator to specify the threshold at which builds should fail. 

One of string: "low" or "medium" or "high" or "critical"

Example configuration : 'Report on all issues, but only fail build for Critical issues'

```yaml
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'mySnykToken'
    testType: 'app'
    failOnThreshold: 'critical'
    monitorWhen: 'always'
```

We're happy to pick this issue up and contribute it back, @maxjeffos sound like a worthwhile feature?
